kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment-demo-green
  labels:
    app: deployment-demo-green
    deployment: green
    version: 1.0.1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment-demo-green
      deployment: green
      version: 1.0.1
  template:
    metadata:
      labels:
        app: deployment-demo-green
        deployment: green
        version: 1.0.1
    spec:
      containers:
        - name: deployment-demo-green
          image: uruku/web:green
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
